# Generated by Django 4.2.24 on 2025-09-22 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
